services:
  app:
    image: autosubmit_models:v1
    build:
      context: ../
      dockerfile: docker/Dockerfile.web
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload 
    volumes: 
      - ../src:/code:rw
    develop:
      watch:
        - action: rebuild
          path: docker/Dockerfile.web
        - action: rebuild
          path: requirements.txt
        - action: rebuild
          path: docker/compose.dev.yaml