services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: autosubmit_models_timescaledb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=timescaledb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d timescaledb"]
      interval: 5s
      timeout: 5s
      retries: 5
