services:
  app:
    image: autosubmit_models:v1
    build:
      context: ../
      dockerfile: docker/Dockerfile.web
    ports:
      - "8002:8002"
    command: uvicorn main:app --host 0.0.0.0 --port 8002
    volumes: 
      - ../src:/code:rw